modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/Quizer9O8/Strata/issues" #optional

[[mods]] #mandatory

modId="strata" #mandatory

<<<<<<< Updated upstream
version="1.0.2" #mandatory
=======
version="1.0.3" #mandatory
>>>>>>> Stashed changes

displayName="Strata" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/Quizer9O8/Strata" #optional

logoFile="strata.png" #optional

credits="Quizer9O8" #optional

authors="Quizer9O8" #optional

description='''Strata is a mod that adds various types of rocks into the game. It changes the look and feel of the game and gives you a plethora of blocks to interact with.'''

[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
